syntax = "proto3";

option csharp_namespace = "CatalogService.Api.Protos";

package catalog;

service CatalogGrpc {
  rpc GetFoodPrice (GetFoodPriceRequest) returns (GetFoodPriceResponse);
  rpc GetFoodPrices (GetFoodPricesRequest) returns (GetFoodPricesResponse);
}

message GetFoodPriceRequest {
  string foodId = 1;
}

message GetFoodPriceResponse {
  double price = 1;
  bool isAvailable = 2;
  string name = 3;
}

message GetFoodPricesRequest {
  repeated string foodIds = 1;
}

message GetFoodPricesResponse {
  map<string, GetFoodPriceResponse> foodPrices = 1;
}
