import type { Metadata } from "next";
import { Edu_SA_Beginner } from "next/font/google"; // Retro Fonts
import "./globals.css";

const eduSA = Edu_SA_Beginner({
  weight: ["400", "700"], // Edu SA supports specific weights
  variable: "--font-edu-sa",
  subsets: ["latin"], // Edu SA likely supports vietnamese, checking docs or defaulting to latin + variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bún Bò chung cư",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${eduSA.variable} antialiased font-main bg-cover bg-fixed bg-center text-text`}
        style={{ backgroundImage: "url('/images/retro-paper-texture.png')", fontFamily: "var(--font-edu-sa)" }}
      >
        {children}
      </body>
    </html>
  );
}
