import type { Metadata } from "next";
import { Roboto_Mono, Plus_Jakarta_Sans } from "next/font/google"; // Added Plus Jakarta Sans
import { Toaster } from "react-hot-toast";
import { Providers } from "./Providers";
import "./globals.css";
import { cn } from "@/lib/utils";

const robotoMono = Roboto_Mono({
  subsets: ["latin", "vietnamese"],
  variable: "--font-roboto-mono",
  display: "swap",
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin", "vietnamese"],
  variable: "--font-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bún Bò chung cư",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", robotoMono.variable, jakarta.variable)} suppressHydrationWarning>
      <body
        className={cn(
          robotoMono.variable,
          jakarta.variable,
          "antialiased font-main bg-cover bg-fixed bg-center text-text"
        )}
        style={{ backgroundImage: "url('/images/retro-paper-texture.png')" }}
      >
        <Providers>
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3500,
              style: {
                fontFamily: "var(--font-roboto-mono)",
                border: "2px solid #2D2D2D",
                borderRadius: "8px",
                boxShadow: "4px 4px 0px #2D2D2D",
                padding: "12px 16px",
              },
              success: {
                iconTheme: { primary: "#D4A853", secondary: "#fff" },
              },
              error: {
                iconTheme: { primary: "#dc2626", secondary: "#fff" },
              },
            }}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}

