import type { Metadata } from "next";
import { Edu_SA_Beginner } from "next/font/google"; // Retro Fonts
import { Toaster } from "react-hot-toast";
import { Providers } from "./Providers";
import "./globals.css";

const eduSA = Edu_SA_Beginner({
  weight: ["400", "700"], // Edu SA supports specific weights
  variable: "--font-edu-sa",
  subsets: ["latin"], // Edu SA likely supports vietnamese, checking docs or defaulting to latin + variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Bún Bò chung cư",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${eduSA.variable} antialiased font-main bg-cover bg-fixed bg-center text-text`}
        style={{ backgroundImage: "url('/images/retro-paper-texture.png')", fontFamily: "var(--font-edu-sa)" }}
      >
        <Providers>
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3500,
              style: {
                fontFamily: "var(--font-edu-sa)",
                border: "2px solid #2D2D2D",
                borderRadius: "8px",
                boxShadow: "4px 4px 0px #2D2D2D",
                padding: "12px 16px",
              },
              success: {
                iconTheme: { primary: "#D4A853", secondary: "#fff" },
              },
              error: {
                iconTheme: { primary: "#dc2626", secondary: "#fff" },
              },
            }}
          />
          {children}
        </Providers>
      </body>
    </html>
  );
}

