apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      nodeSelector:
        role: apps
      containers:
      - name: cart-service
        image: griox/bunbo-cart-service:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "80m"
            memory: "100Mi"
          limits:
            cpu: "400m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10

        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: bunbo-config
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: bunbo-config
              key: Redis__Host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: REDIS_PASSWORD
        - name: ConnectionStrings__Redis
          value: "$(REDIS_HOST),password=$(REDIS_PASSWORD),abortConnect=false"
        - name: GrpcSettings__CatalogUrl
          value: "http://catalog-service:50022"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-service
  minReplicas: 2
  maxReplicas: 4
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15
      - type: Percent
        value: 100
        periodSeconds: 15
      selectPolicy: Max
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
