apiVersion: v1
kind: Secret
metadata:
  name: digitalocean
  namespace: kube-system
stringData:
  # Vui lòng cung cấp DigitalOcean Personal Access Token của bạn tại đây
  # Tạo Token tại: https://cloud.digitalocean.com/account/api/tokens
  access-token: "<YOUR_DO_TOKEN>"
