apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-service
  labels:
    app: realtime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-service
  template:
    metadata:
      labels:
        app: realtime-service
    spec:
      containers:
      - name: realtime-service
        image: griox/bunbo-realtime-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: bunbo-config
        env:
        - name: RabbitMq__Host
          value: "rabbitmq.default.svc.cluster.local"
        - name: RabbitMq__Username
          value: "guest"
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: RABBITMQ_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: bunbo-config
              key: Redis__Host
        - name: Redis__ConnectionString
          value: "$(REDIS_HOST),abortConnect=false"
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-service
spec:
  type: ClusterIP
  selector:
    app: realtime-service
  ports:
  - port: 80
    targetPort: 8080
