apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-service
  labels:
    app: realtime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-service
  template:
    metadata:
      labels:
        app: realtime-service
    spec:
      containers:
      - name: realtime-service
        image: griox/bunbo-realtime-service:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m" # Có thể burst CPU
            memory: "256Mi" # Giới hạn RAM cứng để tránh OOM toàn node
        livenessProbe:
          tcpSocket:
            port: 5005
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 5005
          initialDelaySeconds: 5
          periodSeconds: 10

        ports:
        - containerPort: 5005
        envFrom:
        - configMapRef:
            name: bunbo-config
        env:
        - name: RabbitMq__Host
          value: "rabbitmq.default.svc.cluster.local"
        - name: RabbitMq__Username
          value: "guest"
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: RABBITMQ_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: bunbo-config
              key: Redis__Host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: REDIS_PASSWORD
        - name: Redis__ConnectionString
          value: "$(REDIS_HOST),password=$(REDIS_PASSWORD),abortConnect=false"
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-service
spec:
  type: ClusterIP
  selector:
    app: realtime-service
  ports:
  - port: 80
    targetPort: 5005

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: realtime-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realtime-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
