apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      nodeSelector:
        role: apps
      containers:
      - name: notification-service
        image: griox/bunbo-notification-service:latest
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: bunbo-config
        env:
        - name: JwtSettings__Secret
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: JWT_SECRET
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: RABBITMQ_PASSWORD
        - name: SmtpSettings__Host
          value: "smtp-relay.brevo.com"
        - name: SmtpSettings__Port
          value: "2525"
        - name: SmtpSettings__DefaultSenderEmail
          value: "noreply@bun-bo-chung-cu.io.vn"
        - name: SmtpSettings__SupportSenderEmail
          value: "support@bun-bo-chung-cu.io.vn"
        - name: SmtpSettings__Username
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: SMTP_USERNAME
        - name: SmtpSettings__Password
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: SMTP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 8080
