apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config/app-config.yaml
- config/rabbitmq-deployment.yaml
- cert-manager/cluster-issuer.yaml
- identity/identity-deployment.yaml
- catalog/catalog-deployment.yaml
- cart/cart-deployment.yaml
- order/order-deployment.yaml
- payment/payment-deployment.yaml
- notification/notification-deployment.yaml
- realtime/realtime-deployment.yaml
- promotion/promotion-deployment.yaml
- gateway/gateway-deployment.yaml
- monitoring/seq-deployment.yaml
- monitoring/alert-rules.yaml
- monitoring/podmonitor-microservices.yaml
images:
- name: griox/bunbo-api-gateway
  newName: griox/bunbo-api-gateway
  newTag: 64d87324bc116aee33cfcbaef47f28ba200ba0c9
- name: griox/bunbo-cart-service
  newName: griox/bunbo-cart-service
  newTag: a2c1e82c7ed5a719cdbe85146758b8d22e7e97cb
- name: griox/bunbo-catalog-service
  newName: griox/bunbo-catalog-service
  newTag: 64d87324bc116aee33cfcbaef47f28ba200ba0c9
- name: griox/bunbo-identity-service
  newName: griox/bunbo-identity-service
  newTag: 64d87324bc116aee33cfcbaef47f28ba200ba0c9
- name: griox/bunbo-notification-service
  newName: griox/bunbo-notification-service
  newTag: 64d87324bc116aee33cfcbaef47f28ba200ba0c9
- name: griox/bunbo-order-service
  newName: griox/bunbo-order-service
  newTag: 82a250ee5eb77f8bbc5d1ea627cbd9723a7f27ea
- name: griox/bunbo-payment-service
  newName: griox/bunbo-payment-service
  newTag: 6b7ede8eb72badc925615377ebca349f099c1f0e
- name: griox/bunbo-promotion-service
  newName: griox/bunbo-promotion-service
  newTag: 82a250ee5eb77f8bbc5d1ea627cbd9723a7f27ea
- name: griox/bunbo-realtime-service
  newName: griox/bunbo-realtime-service
  newTag: 64d87324bc116aee33cfcbaef47f28ba200ba0c9
