apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config/app-config.yaml
- config/rabbitmq-deployment.yaml
- cert-manager/cluster-issuer.yaml
- identity/identity-deployment.yaml
- catalog/catalog-deployment.yaml
- cart/cart-deployment.yaml
- order/order-deployment.yaml
- payment/payment-deployment.yaml
- notification/notification-deployment.yaml
- realtime/realtime-deployment.yaml
- promotion/promotion-deployment.yaml
- gateway/gateway-deployment.yaml
- monitoring/seq-deployment.yaml
- monitoring/alert-rules.yaml
- monitoring/podmonitor-microservices.yaml
images:
- name: griox/bunbo-api-gateway
  newName: griox/bunbo-api-gateway
  newTag: 2dbd77f2421e48b5c59bd5b1c3254bf23ea44f37
- name: griox/bunbo-cart-service
  newName: griox/bunbo-cart-service
  newTag: 2dbd77f2421e48b5c59bd5b1c3254bf23ea44f37
- name: griox/bunbo-catalog-service
  newName: griox/bunbo-catalog-service
  newTag: 2dbd77f2421e48b5c59bd5b1c3254bf23ea44f37
- name: griox/bunbo-identity-service
  newName: griox/bunbo-identity-service
  newTag: 2dbd77f2421e48b5c59bd5b1c3254bf23ea44f37
- name: griox/bunbo-notification-service
  newName: griox/bunbo-notification-service
  newTag: 2dbd77f2421e48b5c59bd5b1c3254bf23ea44f37
- name: griox/bunbo-order-service
  newName: griox/bunbo-order-service
  newTag: f94ba0cae6b85d91995d50d71b1e354238047563
- name: griox/bunbo-payment-service
  newName: griox/bunbo-payment-service
  newTag: f94ba0cae6b85d91995d50d71b1e354238047563
- name: griox/bunbo-promotion-service
  newName: griox/bunbo-promotion-service
  newTag: 2dbd77f2421e48b5c59bd5b1c3254bf23ea44f37
- name: griox/bunbo-realtime-service
  newName: griox/bunbo-realtime-service
  newTag: 2dbd77f2421e48b5c59bd5b1c3254bf23ea44f37
