apiVersion: v1
kind: ConfigMap
metadata:
  name: bunbo-config
  namespace: default
data:
  # Các cấu hình dùng chung cho các service (sau này sẽ dùng)
  ASPNETCORE_ENVIRONMENT: "Production"
  Redis__Host: "redis-master.redis.svc.cluster.local:6379"
  Postgres__Host: "postgresql.postgresql.svc.cluster.local"
  Postgres__Port: "5432"
  Postgres__Database: "bunbo_db"
  Postgres__Username: "postgres"
  RabbitMq__Host: "rabbitmq"
  Services__OrderService: "http://order-service"
  # S3 / DigitalOcean Spaces Configuration
  S3Settings__ServiceUrl: "https://s3.ap-southeast-1.amazonaws.com"
  S3Settings__BucketName: "bunbo-bucket"
  S3Settings__Region: "ap-southeast-1"
  # Centralized Logging (Seq)
  Serilog__SeqUrl: "http://seq.monitoring.svc.cluster.local:5341"
  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  # JWT Settings for validation
  JwtSettings__Secret: "SuperSecretKeyForBunBoSystem1234567890"
  JwtSettings__Issuer: "BunBoIdentity"
  JwtSettings__Audience: "BunBoMicroservices"
