apiVersion: v1
kind: Secret
metadata:
  name: bunbo-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded: bunbopw123!
  POSTGRES_PASSWORD: "YnVuYm9wdzEyMyE="
  REDIS_PASSWORD: "YnVuYm9wdzEyMyE="
  # Base64 encoded: Bunbopaymentsupersecret16032004@
  SEPAY_SECRET_KEY: "QnVuYm9wYXltZW50c3VwZXJzZWNyZXQxNjAzMjAwNEA="
  # Base64 encoded: guest
  RABBITMQ_PASSWORD: "Z3Vlc3Q="
  # S3 / DigitalOcean Spaces Credentials (must be Base64 encoded)
  S3_ACCESS_KEY: "<your-base64-access-key>"
  S3_SECRET_KEY: "<your-base64-secret-key>"
