apiVersion: v1
kind: Secret
metadata:
  name: bunbo-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded: bunbopw123!
  POSTGRES_PASSWORD: "YnVuYm9wdzEyMyE="
  REDIS_PASSWORD: "YnVuYm9wdzEyMyE="
