apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: griox/bunbo-payment-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: bunbo-config
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgresql-service;Database=payment_db;Username=postgres;Password=$(Postgres__Password)"
        - name: Postgres__Password
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: POSTGRES_PASSWORD
        - name: SePay__SecretKey
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: SEPAY_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - port: 80
    targetPort: 8080
