apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: griox/bunbo-identity-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: bunbo-config
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: bunbo-config
              key: Postgres__Host
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: bunbo-config
              key: Postgres__Port
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: bunbo-config
              key: Postgres__Database
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: bunbo-config
              key: Postgres__Username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bunbo-secrets
              key: POSTGRES_PASSWORD
        - name: ConnectionStrings__DefaultConnection
          value: "Host=$(POSTGRES_HOST);Port=$(POSTGRES_PORT);Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
